# fly.toml app configuration file generated for ci-cd-test-n2z on 2025-06-01T14:33:17Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ci-cd-test-n2z'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
